# Generated by Cursor on 2026-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worklist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dicomimage",
            name="file_path",
            field=models.FileField(max_length=512, upload_to="dicom/images/"),
        ),
        migrations.AlterField(
            model_name="dicomimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=512, null=True, upload_to="dicom/thumbnails/"
            ),
        ),
    ]

