# Generated by Django 6.0.3 on 2026-04-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist', '0003_study_ai_triage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='contrast_agent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='study',
            name='contrast_used',
            field=models.BooleanField(default=False, help_text='Was contrast agent used?'),
        ),
        migrations.AddField(
            model_name='study',
            name='order_time',
            field=models.DateTimeField(blank=True, help_text='When the study was ordered', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='peer_review_status',
            field=models.CharField(blank=True, choices=[('', 'Not requested'), ('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='study',
            name='qc_flag',
            field=models.BooleanField(default=False, help_text='Quality control flag'),
        ),
        migrations.AddField(
            model_name='study',
            name='radiation_dose',
            field=models.FloatField(blank=True, help_text='Radiation dose in mGy', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='read_start_time',
            field=models.DateTimeField(blank=True, help_text='When radiologist started reading', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='report_time',
            field=models.DateTimeField(blank=True, help_text='When report was completed', null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='requesting_physician',
            field=models.CharField(blank=True, default='', help_text='Ordering/requesting physician', max_length=200),
        ),
        migrations.AddField(
            model_name='study',
            name='second_opinion_requested',
            field=models.BooleanField(default=False, help_text='Second opinion requested'),
        ),
        migrations.AddField(
            model_name='study',
            name='stat_flag',
            field=models.BooleanField(default=False, help_text='STAT/Rush study - requires immediate attention'),
        ),
        migrations.AddField(
            model_name='study',
            name='teaching_file',
            field=models.BooleanField(default=False, help_text='Flag as teaching case'),
        ),
        migrations.AddField(
            model_name='study',
            name='technologist',
            field=models.CharField(blank=True, default='', help_text='Technologist who performed the study', max_length=200),
        ),
    ]
