# Generated by Django 6.0.3 on 2026-04-01 22:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_facility_has_ai_subscription_and_more'),
        ('worklist', '0004_study_contrast_agent_study_contrast_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # All indexes are now defined in models.py Meta classes
    ]
