# Generated by Django 5.2.5 on 2026-01-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='requires_subscription',
            field=models.BooleanField(default=True, help_text='If true, only users with active AI subscription can use this model'),
        ),
    ]
