# Generated by Django 5.2.5 on 2026-01-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='has_ai_subscription',
            field=models.BooleanField(default=False, help_text='Access to AI features'),
        ),
        migrations.AddField(
            model_name='facility',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
