# Generated by Django 6.0.5 on 2026-05-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_facility_has_ai_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='dicom_host',
            field=models.CharField(blank=True, default='', help_text='IP, CIDR, or comma-separated list (e.g. 100.64.0.0/10 or 100.101.2.3). Leave blank to accept from any address.', max_length=200),
        ),
        migrations.AddField(
            model_name='facility',
            name='dicom_port',
            field=models.PositiveIntegerField(default=11112, help_text='DICOM port the facility modality sends on (default 11112).'),
        ),
    ]
