# Generated by Django 6.0.5 on 2026-05-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_dicom_host_port_to_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_facilities',
            field=models.ManyToManyField(blank=True, help_text='Facilities this radiologist reports for. Leave empty if freelancer.', related_name='assigned_radiologists', to='accounts.facility'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False, help_text='Freelancer/guest radiologists can see studies from all facilities.'),
        ),
        migrations.CreateModel(
            name='FacilityModalityNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('CT', 'CT – Computed Tomography'), ('MR', 'MR – Magnetic Resonance'), ('CR', 'CR – Computed Radiography'), ('DX', 'DX – Digital Radiography'), ('DR', 'DR – Digital Radiography (alt)'), ('US', 'US – Ultrasound'), ('MG', 'MG – Mammography'), ('PT', 'PT – PET'), ('NM', 'NM – Nuclear Medicine'), ('XA', 'XA – X-Ray Angiography'), ('RF', 'RF – Radio Fluoroscopy'), ('OT', 'OT – Other')], max_length=16)),
                ('ae_title', models.CharField(blank=True, default='', help_text='AE Title of this modality device (optional).', max_length=32)),
                ('host', models.CharField(blank=True, default='', help_text='IP, CIDR, or comma-separated list for this modality sender.', max_length=200)),
                ('port', models.PositiveIntegerField(default=11112, help_text='DICOM port this modality sends on.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modality_nodes', to='accounts.facility')),
            ],
            options={
                'ordering': ['modality'],
                'unique_together': {('facility', 'modality')},
            },
        ),
    ]
