# Generated by Django 6.0.5 on 2026-05-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_modality_nodes_and_radiologist_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilitymodalitynode',
            unique_together=set(),
        ),
    ]
