# Generated by Django 6.0.5 on 2026-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(blank=True, default='', help_text='Personal UI accent colour override (hex, e.g. #00d4ff). Facility users only; overrides the system default for this account.', max_length=7),
        ),
        migrations.AlterField(
            model_name='facility',
            name='has_ai_subscription',
            field=models.BooleanField(default=False, help_text='Access to AI analysis features'),
        ),
    ]
