from __future__ import annotations

from typing import Dict, List

from django.utils import timezone

from ai_analysis.models import AIAnalysis, AIModel, AutoGeneratedReport
from worklist.models import Study

from .schemas import (
    AIAnalysisRequest,
    AIAnalysisResponse,
    AIAnalysisStatus,
    DashboardSummary,
)


def _filter_models(study: Study, model_ids: List[int]) -> List[AIModel]:
    qs = AIModel.objects.filter(is_active=True)
    if model_ids:
        qs = qs.filter(id__in=model_ids)
    return list(qs)


def start_analysis(payload: AIAnalysisRequest) -> AIAnalysisResponse:
    study = Study.objects.get(id=payload.study_id)
    models = _filter_models(study, payload.model_ids)
    analyses: List[AIAnalysis] = []
    for model in models:
        existing = AIAnalysis.objects.filter(
            study=study,
            ai_model=model,
            status__in=['pending', 'processing', 'completed'],
        ).first()
        if existing:
            continue
        analysis = AIAnalysis.objects.create(
            study=study,
            ai_model=model,
            priority=payload.priority,
            status='pending',
            requested_at=timezone.now(),
        )
        analyses.append(analysis)
    if not analyses:
        return AIAnalysisResponse(success=False, message='No new analyses started')
    # kick background workers via signal/management command (placeholder)
    return AIAnalysisResponse(
        success=True,
        message=f'Started {len(analyses)} AI analyses',
        analysis_ids=[a.id for a in analyses],
    )


def analysis_status(analysis_id: int) -> AIAnalysisStatus:
    analysis = AIAnalysis.objects.select_related('ai_model').get(id=analysis_id)
    progress = 100 if analysis.status == 'completed' else 0
    if analysis.status == 'processing' and analysis.started_at:
        elapsed = (timezone.now() - analysis.started_at).total_seconds()
        estimated = analysis.ai_model.avg_processing_time or 60
        progress = min(95, (elapsed / estimated) * 100)
    details: Dict[str, object] = {
        'model': analysis.ai_model.name,
        'version': analysis.ai_model.version,
        'type': analysis.ai_model.model_type,
        'confidence': analysis.confidence_score,
    }
    if analysis.status == 'completed':
        details.update(
            {
                'findings': analysis.findings,
                'abnormalities_detected': analysis.abnormalities_detected,
                'measurements': analysis.measurements,
            }
        )
    return AIAnalysisStatus(
        id=analysis.id,
        status=analysis.status,
        progress_percentage=round(progress, 2),
        confidence_score=analysis.confidence_score,
        requested_at=analysis.requested_at,
        completed_at=analysis.completed_at,
        details=details,
    )


def dashboard_snapshot() -> DashboardSummary:
    total_models = AIModel.objects.filter(is_active=True).count()
    active_analyses = AIAnalysis.objects.filter(status__in=['pending', 'processing']).count()
    completed_today = AIAnalysis.objects.filter(
        status='completed',
        completed_at__date=timezone.now().date(),
    ).count()
    recent = list(
        AIAnalysis.objects.select_related('study', 'ai_model')
        .order_by('-requested_at')[:10]
        .values('id', 'status', 'study__id', 'ai_model__name', 'requested_at')
    )
    pending_reports = list(
        AutoGeneratedReport.objects.filter(review_status='pending')
        .select_related('study')
        .values('id', 'study__id', 'generated_impression', 'generated_at')[:5]
    )
    return DashboardSummary(
        total_models=total_models,
        active_analyses=active_analyses,
        completed_today=completed_today,
        recent_analyses=recent,
        pending_reports=pending_reports,
    )
