# Generated by Django 6.0.3 on 2026-04-01 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='macrotext',
            name='section',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ReportAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('amendment_reason', models.TextField(blank=True)),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('original_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='reports.report')),
                ('radiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-amended_at'],
            },
        ),
    ]
