"""
Django settings for noctis_pro project.

Generated by 'Django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
import os
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-7x!8k@m$z9h#4p&x3w2v6t@n5q8r7y#3e$6u9i%m&o^2d1f0g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# Tunnel / public URL detection for automatic configuration
#
# Supported:
# - ngrok (NGROK_URL or hosts containing "ngrok")
# - Cloudflare Tunnel quick URL (hosts containing "trycloudflare.com")
# - localtunnel (hosts containing "loca.lt")
NGROK_URL = os.environ.get('NGROK_URL', '')
NGROK_DOMAIN = os.environ.get('NGROK_DOMAIN', '')
NGROK_AUTHTOKEN = os.environ.get('NGROK_AUTHTOKEN', '')
TUNNEL_URL = os.environ.get('TUNNEL_URL', '')

# If a tunnel launcher (e.g., scripts/quick-tunnel.sh or scripts/quick-ngrok.sh)
# is used via systemd or a dev shell, it
# typically writes the public URL to a file (default: $APP_DIR/.tunnel-url).
# Auto-detect that URL so production deployments don't end up rejecting the
# dynamic hostname or generating mixed-scheme links.
APP_DIR = Path(os.environ.get('APP_DIR', str(BASE_DIR)))
_tunnel_url_file_candidates = [
    # Most reliable locations (running app dir)
    APP_DIR / '.tunnel-url',
    BASE_DIR / '.tunnel-url',
    # Common service/deploy locations (some deployments use /opt/noctis-pro)
    Path("/opt/noctispro") / ".tunnel-url",
    Path("/opt/noctis-pro") / ".tunnel-url",
    # Legacy/ops convenience locations
    Path("/etc/noctis-pro") / ".tunnel-url",
    Path("/etc/noctispro") / ".tunnel-url",
]
if not TUNNEL_URL:
    for _p in _tunnel_url_file_candidates:
        try:
            if _p.exists():
                _val = _p.read_text(encoding='utf-8').strip()
                if _val:
                    TUNNEL_URL = _val
                    break
        except Exception:
            # Best-effort: if unreadable, continue without tunnel autodetect.
            pass

# If operators use a reserved ngrok domain, treat that as the tunnel URL.
# This is a common production setup and avoids 400s when the URL file isn't written.
if not TUNNEL_URL and NGROK_DOMAIN:
    TUNNEL_URL = f"https://{NGROK_DOMAIN.strip().lstrip('https://').lstrip('http://').strip('/')}"

_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
_allowed_hosts_tokens = [h.strip().lower() for h in _allowed_hosts_env.split(',') if h.strip()]
#
# Important: In "ngrok mode" without a reserved domain, the actual public URL is
# discovered asynchronously by the tunnel service and written to .tunnel-url
# after ngrok is up. Django settings are only evaluated at process start, so if
# we only infer tunnel mode from TUNNEL_URL/NGROK_URL, Django can permanently
# reject the ngrok Host header with 400 (DisallowedHost) until the server is
# restarted. Keying off NGROK_AUTHTOKEN avoids that boot-order race.
IS_NGROK = bool(NGROK_URL) or bool(NGROK_DOMAIN) or bool(NGROK_AUTHTOKEN) or any(
    'ngrok' in host for host in _allowed_hosts_tokens
)
IS_TUNNEL = bool(TUNNEL_URL) or bool(NGROK_DOMAIN) or bool(NGROK_AUTHTOKEN) or any(
    any(marker in host for marker in ('ngrok', 'trycloudflare.com', 'loca.lt')) for host in _allowed_hosts_tokens
)

# Whether HTTPS is actually configured in front of Django (e.g., nginx + Let's Encrypt).
# This allows safe HTTP-only bootstrapping during first-time certificate issuance.
#
# IMPORTANT: Do NOT infer HTTPS from SECURE_SSL_REDIRECT.
# Misconfigured redirects (or proxies) can otherwise force `*_COOKIE_SECURE=True`
# and break login by preventing the browser from storing the session cookie over HTTP.
SSL_ENABLED = os.environ.get('SSL_ENABLED', '').lower() == 'true'

# Primary public domain (can be overridden via env)
#
# NOTE: Some older deployments/configs used "noctispro.com" (missing hyphen).
# We keep a small compatibility alias so the canonical hostname stays
# "noctis-pro.com" unless the operator explicitly sets a different valid domain.
def normalize_domain_name(value: str) -> str:
    value = (value or "").strip()
    # Accept users pasting full URLs (keep only the hostname).
    if value.startswith("http://"):
        value = value[len("http://") :]
    elif value.startswith("https://"):
        value = value[len("https://") :]
    if "/" in value:
        value = value.split("/", 1)[0]
    value = value.rstrip(".").lower()

    # Legacy alias: preserve the intended public hostname with hyphen.
    if value in {"noctispro.com", "www.noctispro.com", "dicom.noctispro.com"}:
        value = value.replace("noctispro.com", "noctis-pro.com")
    return value

DOMAIN_NAME = normalize_domain_name(os.environ.get('DOMAIN_NAME', 'noctis-pro.com'))
DOMAIN_HOSTS = [h for h in [DOMAIN_NAME, f"www.{DOMAIN_NAME}", f"dicom.{DOMAIN_NAME}"] if h and h != '.']

# Parse ALLOWED_HOSTS safely (ignore blanks/whitespace).
# A common production misconfig is: ALLOWED_HOSTS="example.com, www.example.com"
# which would otherwise include a leading space and trigger DisallowedHost (400).
ALLOWED_HOSTS = [
    h.strip().lower()
    for h in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if h.strip()
]
if DEBUG:
    # Keep dev frictionless unless explicitly locked down
    ALLOWED_HOSTS.append('*')

# Production-safe host handling:
# - Default to DOMAIN_NAME (+ www/dicom) and localhost
# - Allow explicit extras via env
# - Keep legacy/dev hosts only when explicitly enabled
EXTRA_ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('EXTRA_ALLOWED_HOSTS', '').split(',') if h.strip()
]
ALLOW_LEGACY_HOSTS = os.environ.get('ALLOW_LEGACY_HOSTS', '').lower() == 'true'
LEGACY_ALLOWED_HOSTS = [
    'noctis-pro.com',
    # Django's ALLOWED_HOSTS does not support "*." wildcards.
    # Use leading-dot patterns to allow subdomains (and the root domain).
    # See: https://docs.djangoproject.com/en/stable/ref/settings/#allowed-hosts
    '.duckdns.org',
    '.ngrok.io',
    '.ngrok-free.app',
    '.ngrok.app',
    '.trycloudflare.com',
    '.loca.lt',
    '3.222.223.4',
    '172.30.0.2',
]

ALLOWED_HOSTS.extend([
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    *DOMAIN_HOSTS,
    *EXTRA_ALLOWED_HOSTS,
])

# In some container/preview environments, requests may arrive with a Host header
# matching the container hostname (e.g., "cursor"). Allow that hostname so the
# app remains reachable without requiring operators to set ALLOWED_HOSTS.
_runtime_hostname = (os.environ.get("HOSTNAME") or "").strip().lower()
if _runtime_hostname:
    ALLOWED_HOSTS.append(_runtime_hostname)

if DEBUG or IS_TUNNEL or ALLOW_LEGACY_HOSTS:
    ALLOWED_HOSTS.extend(LEGACY_ALLOWED_HOSTS)

# Add specific ngrok URL if provided
if NGROK_URL:
    # Extract domain from full URL
    import re
    ngrok_domain = re.sub(r'^https?://', '', NGROK_URL.strip('/'))
    ALLOWED_HOSTS.append(ngrok_domain)

# Add reserved ngrok domain (host only)
if NGROK_DOMAIN:
    ALLOWED_HOSTS.append(NGROK_DOMAIN.strip().rstrip('.').lower())

# Add specific tunnel URL host if provided (e.g., https://xxxx.trycloudflare.com)
if TUNNEL_URL:
    import re
    tunnel_domain = re.sub(r'^https?://', '', TUNNEL_URL.strip('/'))
    ALLOWED_HOSTS.append(tunnel_domain)

# Remove duplicates and empty strings
ALLOWED_HOSTS = list(filter(None, list(set(ALLOWED_HOSTS))))


# Application definition

INSTALLED_APPS = [
    'daphne',  # Re-enabled for ASGI support
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',  # Re-enabled for API access
    'channels',  # Re-enabled for WebSocket support
    
    # Custom apps - ENABLED FOR MEDICAL EMERGENCY
    'accounts',
    'worklist',  # ENABLED - CRITICAL FOR PATIENT DATA ACCESS
    'dicom_viewer',  # ENABLED - CRITICAL FOR MEDICAL IMAGING
    'reports',  # ENABLED - CRITICAL FOR MEDICAL REPORTS
    'admin_panel',  # ENABLED - CRITICAL FOR SYSTEM MANAGEMENT
    'chat',  # ENABLED - CRITICAL FOR MEDICAL COMMUNICATION
    'notifications',  # ENABLED - CRITICAL FOR MEDICAL ALERTS
    'ai_analysis',  # ENABLED - CRITICAL FOR MEDICAL AI
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Re-enabled
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'noctis_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'noctis_pro.wsgi.application'
ASGI_APPLICATION = 'noctis_pro.asgi.application'  # Re-enabled for Daphne

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Redis configuration for channels - Disabled for now to fix login
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('127.0.0.1', 6379)],
#         },
#     },
# }

# Use in-memory channel layer for now
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Celery Configuration - Disabled for now to fix login
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['application/json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
#
# Allow deployments (systemd/docker) to persist static/media outside the code directory.
STATIC_URL = os.environ.get('STATIC_URL', '/static/')
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
_extra_static_dir = os.path.join(BASE_DIR, 'static')
os.makedirs(_extra_static_dir, exist_ok=True)
STATICFILES_DIRS = [_extra_static_dir]

# Serving user-uploaded media via Django is convenient for dev/tunnels but is not a
# production-grade default. In production, serve `MEDIA_URL` via your reverse proxy
# (nginx/Apache/S3) and keep this disabled.
_serve_media_default = 'True' if DEBUG else 'False'
SERVE_MEDIA_FILES = os.environ.get('SERVE_MEDIA_FILES', _serve_media_default).lower() == 'true'

# Configure MIME types for static files
import mimetypes
mimetypes.add_type('application/javascript', '.js')
mimetypes.add_type('text/css', '.css')
mimetypes.add_type('application/json', '.json')

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# DICOM files storage
DICOM_ROOT = os.path.join(MEDIA_ROOT, 'dicom')

# Ensure media directories exist (uploads must persist to disk).
# In some deployments the volume is mounted but the directory isn't created yet,
# which causes uploads to silently fail at the storage layer.
try:
    os.makedirs(MEDIA_ROOT, exist_ok=True)
    os.makedirs(DICOM_ROOT, exist_ok=True)
except Exception:
    # Don't crash settings import; storage errors will surface during request handling/logging.
    pass

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Local web port (used for docker-compose host publishing).
# When running behind a reverse proxy, this may differ, but having it here
# avoids CSRF/CORS breakage when operators change WEB_PORT to avoid conflicts.
try:
    WEB_PORT = int(os.environ.get("WEB_PORT", "8000"))
except Exception:
    WEB_PORT = 8000

# CORS settings for ngrok and deployment
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
]

# Allow overriding/adding CORS origins via env (comma-separated).
_cors_allowed_origins_env = os.environ.get("CORS_ALLOWED_ORIGINS", "")
if _cors_allowed_origins_env.strip():
    CORS_ALLOWED_ORIGINS.extend(
        [o.strip() for o in _cors_allowed_origins_env.split(",") if o.strip()]
    )

# Ensure the configured local web port is permitted (common when WEB_PORT != 8000).
for _origin in (
    f"http://localhost:{WEB_PORT}",
    f"http://127.0.0.1:{WEB_PORT}",
    f"https://localhost:{WEB_PORT}",
    f"https://127.0.0.1:{WEB_PORT}",
):
    if _origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_origin)

# Add configured domain(s) to CORS
if DOMAIN_HOSTS:
    CORS_ALLOWED_ORIGINS.extend(
        [f"https://{h}" for h in DOMAIN_HOSTS] + [f"http://{h}" for h in DOMAIN_HOSTS]
    )

# Add specific ngrok URL to CORS if provided
if NGROK_URL:
    CORS_ALLOWED_ORIGINS.extend([
        NGROK_URL,
        NGROK_URL.replace('https://', 'http://') if NGROK_URL.startswith('https://') else NGROK_URL.replace('http://', 'https://')
    ])

# Add specific tunnel URL to CORS if provided
if TUNNEL_URL:
    CORS_ALLOWED_ORIGINS.extend([
        TUNNEL_URL,
        TUNNEL_URL.replace('https://', 'http://') if TUNNEL_URL.startswith('https://') else TUNNEL_URL.replace('http://', 'https://')
    ])

# Add ngrok support dynamically
CORS_ALLOW_ALL_ORIGINS = DEBUG or IS_TUNNEL  # Allow all origins in debug mode or when using a tunnel

CORS_ALLOW_CREDENTIALS = True

# CSRF trusted origins - Fix for 403 errors and ngrok support
CSRF_TRUSTED_ORIGINS = [
    f"http://{DOMAIN_NAME}",
    f"https://{DOMAIN_NAME}",
    "https://*.ngrok.io",
    "https://*.ngrok-free.app",
    "https://*.ngrok.app",
    "http://*.ngrok.io",
    "http://*.ngrok-free.app", 
    "http://*.ngrok.app",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:80",
    "http://127.0.0.1:80",
    "http://localhost",
    "http://127.0.0.1",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
    "https://*.duckdns.org",
    "https://*.trycloudflare.com",
    "http://*.trycloudflare.com",
    "https://*.loca.lt",
    "http://*.loca.lt",
    "http://*.duckdns.org",
]

# Allow overriding/adding CSRF trusted origins via env (comma-separated).
_csrf_trusted_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if _csrf_trusted_origins_env.strip():
    CSRF_TRUSTED_ORIGINS.extend(
        [o.strip() for o in _csrf_trusted_origins_env.split(",") if o.strip()]
    )

# Ensure the configured local web port is trusted (common when WEB_PORT != 8000).
for _origin in (
    f"http://localhost:{WEB_PORT}",
    f"http://127.0.0.1:{WEB_PORT}",
    f"https://localhost:{WEB_PORT}",
    f"https://127.0.0.1:{WEB_PORT}",
):
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

# Add configured domain(s) to CSRF trusted origins
if DOMAIN_HOSTS:
    CSRF_TRUSTED_ORIGINS.extend(
        [f"https://{h}" for h in DOMAIN_HOSTS] + [f"http://{h}" for h in DOMAIN_HOSTS]
    )

# Add specific ngrok URL to CSRF trusted origins if provided
if NGROK_URL:
    CSRF_TRUSTED_ORIGINS.extend([
        NGROK_URL,
        NGROK_URL.replace('https://', 'http://') if NGROK_URL.startswith('https://') else NGROK_URL.replace('http://', 'https://')
    ])

# Add specific tunnel URL to CSRF trusted origins if provided
if TUNNEL_URL:
    CSRF_TRUSTED_ORIGINS.extend([
        TUNNEL_URL,
        TUNNEL_URL.replace('https://', 'http://') if TUNNEL_URL.startswith('https://') else TUNNEL_URL.replace('http://', 'https://')
    ])

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/worklist/'
LOGOUT_REDIRECT_URL = '/login/'

# Session configuration - Use database sessions instead of Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# 30 minutes inactivity timeout
SESSION_COOKIE_AGE = 1800
# Refresh expiry on each request to implement inactivity-based expiry
SESSION_SAVE_EVERY_REQUEST = True
# Expire session at browser close to require fresh login on new window
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# File upload settings
# - Allow up to 5GB total upload payloads (e.g., large DICOM batches)
# - Keep per-file in-memory buffering modest so large files stream to disk
MAX_UPLOAD_SIZE_BYTES = 5 * 1024 * 1024 * 1024  # 5GB
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE_BYTES
DATA_UPLOAD_MAX_NUMBER_FILES = 5000  # Support for up to 5000 uploaded files per request
DATA_UPLOAD_MAX_NUMBER_FIELDS = 15000  # Support for up to 5000 images with metadata
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50MB

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN' if DEBUG or IS_TUNNEL else 'DENY'  # Allow embedding for tunnels/dev

# Tunnel-specific security adjustments
if IS_TUNNEL:
    # Disable some security features that interfere with tunnels (host/origin changes)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    # But keep others for security
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

# Production security enhancements (only if not using ngrok)
if not DEBUG and not IS_NGROK:
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True' if SSL_ENABLED else 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True' if SSL_ENABLED else 'False').lower() == 'true'
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True' if SSL_ENABLED else 'False').lower() == 'true'

    # Only enable HSTS when HTTPS is confirmed enabled, otherwise it can lock browsers onto HTTPS.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000' if SSL_ENABLED else '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SSL_ENABLED and os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
    SECURE_HSTS_PRELOAD = SSL_ENABLED and os.environ.get('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True

# Emergency escape hatch for deployments that are HTTP-only (or tunnels) where
# secure cookies cause a post-login redirect loop. Prefer enabling HTTPS and
# setting SSL_ENABLED=true in production; use this only to restore access.
if os.environ.get('FORCE_INSECURE_COOKIES', '').lower() in ('1', 'true', 'yes', 'on'):
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Database
# Production database configuration with fallback to SQLite
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', ''),
    }
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'noctis_pro.log'),
            'maxBytes': 10*1024*1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 5*1024*1024,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': False,
        },
        'noctis_pro': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'noctis_pro.upload': {
            'handlers': ['file', 'console'] if DEBUG else ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'worklist': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# Performance settings for production
if not DEBUG:
    # Database connection pooling
    DATABASES['default']['CONN_MAX_AGE'] = 60
    
    # Cache static file serving
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Ngrok-specific settings for better performance
if IS_NGROK:
    # Already set above for all environments
    # Disable some checks that can cause issues with ngrok
    USE_TZ = True
    
print(f"🚀 Noctis Pro PACS Settings Loaded:")
print(f"   • Debug Mode: {DEBUG}")
print(f"   • Ngrok Mode: {IS_NGROK}")
print(f"   • Ngrok URL: {NGROK_URL or 'Not set'}")
print(f"   • Allowed Hosts: {len(ALLOWED_HOSTS)} configured")
print(f"   • Database: {DATABASES['default']['ENGINE'].split('.')[-1]}")
print(f"   • Security: {'Development' if DEBUG else 'Production'} profile")


# Masterpiece overrides removed to allow dynamic configuration via environment and NGROK_URL
#
# Proxy header handling:
# - We always *support* a reverse-proxy/TLS-terminator by honoring X-Forwarded-Proto
#   (this is required for HTTPS links when TLS terminates in front of Django).
# - But we **do not** trust X-Forwarded-Host/Port by default.
#   Trusting those headers can make the app "stick" to an ngrok hostname (or any
#   client-supplied value) and appear like ngrok is overriding everything.
#
# If you are behind nginx/Cloudflare/ELB and need forwarded host/port, explicitly
# set USE_X_FORWARDED_HOST=True and/or USE_X_FORWARDED_PORT=True in the environment.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = os.environ.get('USE_X_FORWARDED_HOST', 'False').lower() == 'true'
USE_X_FORWARDED_PORT = os.environ.get('USE_X_FORWARDED_PORT', 'False').lower() == 'true'

# DICOM viewer masterpiece settings
def _env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name, None)
    if raw is None or str(raw).strip() == "":
        return default
    return str(raw).strip().lower() in ("1", "true", "yes", "on")

# Production hardening flags (safe-by-default):
# - Desktop launch: running local subprocesses from HTTP requests is unsafe in production.
# - Local directory import: scanning server paths is unsafe unless explicitly restricted.
# - C++ compat API: legacy endpoints can expose sensitive info; keep off unless needed.
DICOM_VIEWER_ENABLE_DESKTOP_LAUNCH = _env_bool("DICOM_VIEWER_ENABLE_DESKTOP_LAUNCH", default=False)
DICOM_VIEWER_ENABLE_LOCAL_DIRECTORY_IMPORT = _env_bool("DICOM_VIEWER_ENABLE_LOCAL_DIRECTORY_IMPORT", default=DEBUG)
DICOM_VIEWER_ENABLE_CPP_COMPAT_API = _env_bool("DICOM_VIEWER_ENABLE_CPP_COMPAT_API", default=False)
DICOM_VIEWER_ENABLE_PREPROCESSING = _env_bool("DICOM_VIEWER_ENABLE_PREPROCESSING", default=True)

# Background preprocessing (single-core by default).
try:
    DICOM_VIEWER_PREPROCESS_WORKERS = int(os.environ.get("DICOM_VIEWER_PREPROCESS_WORKERS", "1"))
except Exception:
    DICOM_VIEWER_PREPROCESS_WORKERS = 1
try:
    DICOM_VIEWER_PREPROCESS_MAX_SERIES = int(os.environ.get("DICOM_VIEWER_PREPROCESS_MAX_SERIES", "4"))
except Exception:
    DICOM_VIEWER_PREPROCESS_MAX_SERIES = 4

# If local directory import is enabled, restrict imports to these roots (best-effort).
# Operators can override with a comma-separated list of absolute paths.
_import_roots_env = os.environ.get("DICOM_VIEWER_IMPORT_ROOTS", "").strip()
if _import_roots_env:
    DICOM_VIEWER_IMPORT_ROOTS = [p.strip() for p in _import_roots_env.split(",") if p.strip()]
else:
    # Conservative defaults for typical removable-media mount points.
    DICOM_VIEWER_IMPORT_ROOTS = ["/media", "/mnt", "/run/media", "/Volumes"]

DICOM_VIEWER_SETTINGS = {
    'MAX_UPLOAD_SIZE': MAX_UPLOAD_SIZE_BYTES,  # 5GB
    'SUPPORTED_MODALITIES': ['CT', 'MR', 'CR', 'DX', 'US', 'XA'],
    'CACHE_TIMEOUT': 3600,
    'ENABLE_3D_RECONSTRUCTION': True,
    'ENABLE_MEASUREMENTS': True,
    'ENABLE_ANNOTATIONS': True,
    'ENABLE_AI_ANALYSIS': True,
    'ENABLE_QR_CODES': True,
    'ENABLE_LETTERHEADS': True,
    'ENABLE_DESKTOP_LAUNCH': DICOM_VIEWER_ENABLE_DESKTOP_LAUNCH,
    'ENABLE_LOCAL_DIRECTORY_IMPORT': DICOM_VIEWER_ENABLE_LOCAL_DIRECTORY_IMPORT,
    'ENABLE_CPP_COMPAT_API': DICOM_VIEWER_ENABLE_CPP_COMPAT_API,
    'ENABLE_PREPROCESSING': DICOM_VIEWER_ENABLE_PREPROCESSING,
}
