# Generated by Django 4.2.24 on 2025-09-07 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangingProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('body_part', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('layout', models.CharField(default='1x1', max_length=32)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HounsfieldQAPhantom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('water_roi_coordinates', models.JSONField(help_text='ROI coordinates for water measurement')),
                ('air_roi_coordinates', models.JSONField(help_text='ROI coordinates for air measurement')),
                ('material_rois', models.JSONField(default=dict, help_text='Additional material ROI coordinates')),
                ('expected_water_hu', models.FloatField(default=0.0)),
                ('expected_air_hu', models.FloatField(default=-1000.0)),
                ('expected_materials', models.JSONField(default=dict, help_text='Expected HU values for materials')),
                ('water_tolerance', models.FloatField(default=5.0)),
                ('air_tolerance', models.FloatField(default=50.0)),
                ('material_tolerances', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklist.study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconstructionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('mpr', 'Multiplanar Reconstruction'), ('mip', 'Maximum Intensity Projection'), ('bone_3d', 'Bone 3D Reconstruction'), ('mri_3d', 'MRI 3D Reconstruction')], max_length=20)),
                ('parameters', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklist.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('length', 'Length'), ('area', 'Area'), ('angle', 'Angle'), ('cobb_angle', 'Cobb Angle')], max_length=20)),
                ('points', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(default='mm', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklist.dicomimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HounsfieldCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('station_name', models.CharField(blank=True, max_length=100)),
                ('device_serial_number', models.CharField(blank=True, max_length=100)),
                ('rescale_slope', models.FloatField()),
                ('rescale_intercept', models.FloatField()),
                ('rescale_type', models.CharField(blank=True, max_length=20)),
                ('water_hu', models.FloatField(blank=True, null=True)),
                ('air_hu', models.FloatField(blank=True, null=True)),
                ('noise_level', models.FloatField(blank=True, null=True)),
                ('calibration_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('warning', 'Warning'), ('not_applicable', 'Not Applicable'), ('error', 'Error')], max_length=20)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('water_deviation', models.FloatField(blank=True, null=True)),
                ('air_deviation', models.FloatField(blank=True, null=True)),
                ('linearity_check', models.FloatField(blank=True, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('phantom_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklist.series')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hu_calibrations', to='worklist.study')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('text', models.TextField()),
                ('color', models.CharField(default='#FFFF00', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklist.dicomimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WindowLevelPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('body_part', models.CharField(blank=True, max_length=64)),
                ('window_width', models.FloatField()),
                ('window_level', models.FloatField()),
                ('inverted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'modality', 'body_part')},
            },
        ),
    ]
